### ISSUE TITLE
Ability to specify vis options per rectangle, and force rotation on

### ISSUE THREAD

**Issue by neekfenwick** [dagmike/BinPacking#11]
Hi, me again :) I'm adding features to our system and find I'd like to modify the library some more.  Two main requirements:

1/ Ability to change font size per rectangle in the visualisation.  Some of our items are very small, others very large.  For the small ones the text label overlaps the edge of the rectangle.
Proposed solution: Add a new member to Rectangle $visOptsOverrides to allow 'fontSize' to be overridden, used instead of the $visOpts passed to generateVisualisation().  This is pretty straightforward and backwardly compatible (new constructor arg with default = null).

2/ Ability to force rectangles to be rotated instead of leaving it up to the algorithm and Rectangle::isFlipAllowed().
Proposed solution: I'd like your feedback on this if possible.  The Rectangle::$allowFlip member lets you say if a rectangle may be flipped, but if true then the layout algorithms decide whether to flip based on available space.
Reason: We print mostly rectangular items on a printer bed, and sometimes by rotating all items to be portrait instead of horizontal lets us squeeze another item or two on the bed.  In this case we always rotate every landscape item.  So we would inspect each candidate rectangle, if it is landscape then force rotation on.

The problem is that this kind of conflicts with $allowFlip.  Adding a second member $forceFlip seems messy.  It's almost like we need a 3 state enum, 'no flip', 'allow flip' and 'force flip'.  This would not be backward compatible, unless we take advantage of PHP's loose type system and allow the $allowFlip constructor arg to be either boolean or enum and do some nasty value testing.

I'll work on this and deliver a PR eventually but would welcome your input.

**Comment by neekfenwick** [comment]
I misspoke, it's not `Rectangle::$allowFlip`, it's RectangleBinPack::$allowFlip, so on `master` the bin holds knowledge of whether rectangles may be rotated.  I'm now needing to override this on a per-rectangle basis, so I need to add `$allowFlip` to the rectangles too.

I'm making FlipType be a class with 3 members (I'm stuck on PHP 7 so cannot use `enum`) of NoFlip, AllowFlip and ForceFlip, allowing the algorithm to decide whether to flip each rect or not based on its setting.

It's going well, I run the packing algo once using normal settings, then again with each rect set to `ForceFlip`, and compare the number of used rectangles.  If the `ForceFlip` case fits more on the bed, we use that one, otherwise the first one.  This is likely to save quite a bit of time and hassle in our print room.

**Comment by neekfenwick** [comment]
I've run into new requirements :) I've decided to extend the RectangleBinPack class, because I need to do some post-processing after the `insertMany()` processing and mess with the packed rectangles, and found the members are all private, so I need to make them protected for my case.  That's the only further change at this point but I'll re-issue my PR soon.

**Comment by neekfenwick** [comment]
I updated the Pull Request a while back, and news on getting it merged, please?

**Comment by dagmike** [comment]
Sorry man, I've been away again and need to properly sit down to try and
resolve that merge conflict.
But without me having written the code myself it's going to take me some
time.
I'll try to get it done tonight.
