### ISSUE TITLE
Rendering labels on rects, arbitrary rect data and Linear layout

### ISSUE THREAD

**Issue by neekfenwick** [dagmike/BinPacking#5]
I've run into this library and started using it for our project, and found I need to make some modifications.  They're generally pretty useful and I hope you guys would accept a PR with the changes.  We're using the library to assist laying out physical products, and require the following:

1/ Each of our products is represented as a Rectangle in the algorithm, and needs to carry its ID value through, so that once packed we can inspect which product was put where.
2/ The Visualisation needs to render a label for each rect to indicate which one it is.
3/ One of our processes requires laying products out in a simple line, without the 2d element of packing.
4/ We need to maintain a gap between products.

To achieve these, I've made the following changes:

1/ Add a 'data' attribute to the Rectangle class so you can associate an arbitrary array of data with each one.  This can then be used after packing to relate each packed Rectangle with the original input data.
2/ Add a 'label' attribute to the Rectangle class, and modify the Visualisation class to take an $opts object with directives such as font file, size etc, and render the label in the center of each Rect.
3/ Add a Linear algorithm that simply lays items out horizontally, optionally rotating if it would make the rect occupy less space.
4/ Add an isHollow attribute to WindowedRectangle that makes them solid, so that free rectangles are not created in their inside.  This allows them to be used to simulate a margin between rectangles while retaining the 'width' and 'height' concept of the rect.

It would be awesome if I could submit a PR with these changes for your review, what do you think of the changes in general?

**Comment by dagmike** [comment]
Hi man, those changes sound great to me and also don't sound like they would break anything either so please feel free to submit a PR!

I'm interested to see how the isHollow attribute allows it to be used to simulate margins.

**Comment by neekfenwick** [comment]
Glad to hear you're so welcoming :) What we found with the WindowedRectangle was that the algorithm creates a 'free' rectangle inside it.  It's not clear to me what your use case was for that type of rectangle but this 'free' rectangle caused other, smaller rectangles to be packed inside that window space.

Our situation is that our products must be, say, 10cm apart, so for a 60cm x 60cm item, I create a WindowedRectangle with width and height 60 and a border of 5 on each side.  This simulates the item itself being 60cm and maintains the 10cm border.  On the diagram all rectangles may touch each other on the edges, but we know that in the real world our staff will place the 60x60 product in the 'window' area and thus maintain the gap.

It was trivial to add an isHollow attribute to the WindowedRectangle which defaults true, and edit the algorithm code so it only creates that inner 'free' rectangle if isHollow == true.

I've maintained backward compatibility everywhere I've edited, making sure any new parameters are added to the end of constructor argument lists and given default values.

I'm going away tomorrow for 4 days and we're still polishing the code.  Your scoring system in the packing algorithms is still pretty confusing, and text rendering via Imagick is really annoying.  I've forked the repo and will commit something probably early next week you can take a look at.

**Comment by dagmike** [comment]
Yeah I thought the windowed rectangle might confuse people slightly. I work for a business that makes picture frames and one of the products we sell is mountboard with an aperture (opening in the middle). We buy the mountboard in large sheets and use a machine to cut it so we are able to us the middles that are going to be cut out of large mounts to cut other smaller mounts - hence the free rectangle being in the middle.

Bit of an odd use case I'll admit ha, to be quite honest I just ported this code over from a C++ library and thought I'd make the repo public in case anyone else would find it useful so any and all tweaks are welcome especially if they add the sort of functionality you are talking about.

And now I see how you use the WindowedRectangle for a margin, nice one. With the scoring system I agree it's all a bit confusing but as I say I didn't really work hard to understand how it worked more just to get it to work as the company I work for needed it very fast. And Imagick is just annoying in general haha, if it were down to me then none of this would be written in PHP but sadly it isn't down to me ha.

I look forward to seeing then changes you've made, thanks again man :)
