### ISSUE TITLE
Linear algorithm should order items from tallest to shortest, rather than widest to narrowest.

### ISSUE THREAD

**Issue by neekfenwick** [dagmike/BinPacking#8]
A bit of a personal requirement here, but since the last PR we've realised our team needs the items laid out linearly with the tallest item first and sorted in order of height.  It's a very simple change to the score values returned by the Linear algorithm.  I'll make a new PR, you can take a look.

**Comment by dagmike** [comment]
Should all be merged and the new release sorted now thanks.

**Comment by neekfenwick** [comment]
Awesome, thanks dude :)
